import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  const pathname = typeof window !== 'undefined' ? window.location.pathname : '';
  // Helper to check if a link is active
  const isActive = (href: string) => pathname.startsWith(href);

  return (
    <header className="header" style={{ position: 'sticky', top: 0, zIndex: 100 }}>
      <nav className="header-content">
        <div className="header-logo">
          <span style={{ fontSize: 28, color: '#a5b4fc' }}>💊</span>
          Oxyera Health
        </div>
        <div className="header-nav">
          <Link href="/patients" className={isActive('/patients') ? 'active-link' : ''}>Patients</Link>
          <Link href="/medications" className={isActive('/medications') ? 'active-link' : ''}>Medications</Link>
          <Link href="/assignments" className={isActive('/assignments') ? 'active-link' : ''}>Assignments</Link>
          <Link href="/medications/new" className="button" style={{ marginLeft: 16 }}>Add Medication</Link>
        </div>
      </nav>
    </header>
  );
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
